name: Deploy to Heroku

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Build and push Docker image
        env:
          HEROKU_APP_NAME: video-editing-core
        run: |
          docker-compose build
          docker tag yourservice:latest registry.heroku.com/$HEROKU_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: your-heroku-app-name
        run: |
          curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
          -d '{
            "updates": [
              {
                "type": "web",
                "docker_image": "'"$(docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}})"'"
              }
            ]
          }' \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer $HEROKU_API_KEY"
